# Generated by Django 5.0.8 on 2024-09-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptionprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Features for pricing, separated by new line', null=True),
        ),
    ]
