# Generated by Django 5.0.14 on 2026-02-11 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='is_repeatable',
        ),
        migrations.AddField(
            model_name='chore',
            name='chore_type',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('DAILY', 'Daily')], default='ONE_TIME', max_length=20),
        ),
        migrations.CreateModel(
            name='ChoreCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
